name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        environment:
          - atc-2020
          - aoj
          - codeforces
          - codingame
          - library-checker
          - yukicoder

        include:
          - environment: atc-2020
            toolchain: 1.42.0-x86_64-unknown-linux-gnu
            os: ubuntu-latest
            clippy: true
          - environment: aoj
            toolchain: 1.41.1-x86_64-unknown-linux-gnu
            os: ubuntu-latest
            clippy: true
            # FIXME: AOJ uses 2015 edition!
          - environment: codeforces
            toolchain: 1.49.0-x86_64-unknown-linux-gnu
            os: ubuntu-latest
            clippy: true
          - environment: codingame
            toolchain: 1.38.0-x86_64-unknown-linux-gnu
            os: ubuntu-latest
            clippy: true
          - environment: library-checker
            toolchain: 1.47.0-x86_64-unknown-linux-gnu
            os: ubuntu-latest
            clippy: true
          - environment: yukicoder
            toolchain: 1.50.0-x86_64-unknown-linux-gnu
            os: ubuntu-latest
            clippy: true
    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: "`git config --global core.autocrlf false`"
        run: git config --global core.autocrlf false
        if: matrix.os == 'windows-latest'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: default

      - name: "`cargo clippy --all-targets --profile test -- -D warnings`"
        if: matrix.clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --profile test -- -D warnings

      - name: "cargo test"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features ${{ matrix.environment }}
